name: .c_invoice
channels:
    - nodefaults
dependencies:
    - alabaster
    - astroid
    - attrs
    - Babel
    - bandit
    - beautifulsoup4
    - black
    - certifi
    - cffi
    - charset-normalizer
    - click
    - cryptography
    - css-html-js-minify
    - dnspython
    - docformatter
    - docopt
    - docutils
    - elementpath
    - Faker
    - fett
    - flake8
    - ghp-import
    - gitdb
    - GitPython
    - idna
    - imagesize
    - importlib-metadata
    - iniconfig
    - isort
    - Jinja2
    - lazy-object-proxy
    - lxml
    - Markdown
    - MarkupSafe
    - mccabe
    - mergedeep
    - mkdocs
    - mkdocs-autorefs
    - mkdocs-bootstrap
    - mkdocs-material
    - mkdocs-material-extensions
    - mkdocstrings
    - mypy
    - mypy-extensions
    - networkx
    - packaging
    - pathspec
    - pbr
    - platformdirs
    - pluggy
    - py
    - pycodestyle
    - pycparser
    - pydocstyle
    - pyflakes
    - Pygments
    - pylint
    - pymdown-extensions
    - pymongo
    - pyparsing
    - pytest
    - python-dateutil
    - python-dotenv
    - python-jsonrpc-server
    - python-slugify
    - pytkdocs
    - pytz
    - PyYAML
    - pyyaml_env_tag
    - requests
    - six
    - smmap
    - snowballstemmer
    - soupsieve
    - Sphinx
    - sphinx-material
    - sphinxcontrib-applehelp
    - sphinxcontrib-devhelp
    - sphinxcontrib-htmlhelp
    - sphinxcontrib-jsmath
    - sphinxcontrib-qthelp
    - sphinxcontrib-serializinghtml
    - stevedore
    - text-unidecode
    - toml
    - tomli
    - toposort
    - typing_extensions
    - ujson
    - Unidecode
    - untokenize
    - urllib3
    - watchdog
    - wrapt
    - xmlschema
    - xsdata
    - zipp