site_name: e-Invoice Onboarding Toolkit
site_url: https://github.com/BPC-OpenSourceTools/e-Invoice-Onboarding-Toolkit
#edit_uri: ./discovery/docs/
repo_name: e-Invoice Onboarding Toolkit
repo_url: https://github.com/BPC-OpenSourceTools/e-Invoice-Onboarding-Toolkit
docs_dir: docs


theme:
  name: material
  icon:
    logo: material/xml
  palette:
   primary: pink
   accent: lime green
  font:
    text: Poppins
    code: Roboto Mono

plugins:
  - search
  #- mkdocstrings

markdown_extensions:
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: true

nav:
  - FAQ: faq.md
  - Project Home: index.md
  - Getting Started: getting_started.md
  - Tools and Resources: tools_and_resources.md
  - Configuring a Development Environment: python_dev_env.md
  - Package Requirements: requirements.md
  - Working with the Code: working_with_the_code.md
  - Using the Code:
    - The Modules: using_the_modules.md
    - Start-to-Finish: start_to_finish.md
    - Test Cases: test_cases.md
    - Google Colab Pages: google_colab_pages.md
    - Package/Library API:
      - accessor.py: accessor.md
      - app_logging.py: app_logging.md
      - create_tracking_id.py: create_tracking_id.md
      - dns_query.py: dns_query.md
      - discovery_message_package.py: einvoice_message_package.md
      - line_item.py: line_item.md
      - party_address.py: party_address.md
      - semantic_model.py: semantic_model.md
      - smp_query.py: smp_query.md
      - urn_handler.py: urn_handler.md
      - urn_hasher.py: urn_hasher.md
      - urn.py: urn.md
    - Flask Integration on Docker: flask_integration_on_docker.md
  - Project Roadmap: project_roadmap.md
  - Enabling Infrastructure Components: enabling_infrastructure_components.md
  - To do: todo.md
  - Project Artifacts: artifacts.md
  - Workflow: git_workflow.md
  - OASIS Documentation: oasis_documentation.md
  - License: _license.md
