site_name: E-Invoice Onboarding Toolkit
site_url: https://github.com/BPC-Exchange-Framework/E-Invoice-Onboarding-Toolkit
#edit_uri: ./discovery/docs/
repo_name: E-Invoice Onboarding Toolkit
repo_url: https://github.com/BPC-Exchange-Framework/E-Invoice-Onboarding-Toolkit
docs_dir: docs


theme:
  name: material
  # name: mkdocs
  # name: readthedocs
  icon:
    logo: material/xml

  custom_dir: overrides
  config.extra.generator: false

  palette:
    - primary: blue grey
      accent: deep orange
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - primary: cyan
      accent: deep orange
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Poppins
    # text: Roboto
    # text: "Noto Sans"
    # text: Ubuntu
    # text: Red Hat Text
    code: Roboto Mono

extra_css:
  - css/extra.css

copyright: Copyright &copy; 2022 - BPC Exchange Framework Open Source Tools Project

markdown_extensions:
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: true
  # - mkautodoc
  - attr_list
  - md_in_html


plugins:
  - search
  #- mkdocstrings
  - print-site:
      add_to_navigation: true
      print_page_title: 'Print the Documentation'
      add_print_site_banner: false
      # Table of contents
      add_table_of_contents: true
      toc_title: 'Table of Contents'
      toc_depth: 3
      # Content-related
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: ""
      include_css: true
      enabled: true
      exclude:


nav: 
  - Project Home: index.md
  - FAQ: faq.md
  - Outcomes: outcomes.md
  - Assumptions: assumptions.md
  - Tools and Resources: tools_and_resources.md
  - Configure a Python Dev Environment: python_dev_env.md
  - Package Requirements: requirements.md
  - Getting the Code: working_with_the_code.md
  - Using the Code:
    - SML Hash Functionality: sml_hash_func.md
    - DNS Query for SML urn: dns_query_sml.md
    - SMP REST API Query: smp_rest_query.md
    - Test Cases: test_cases.md
    - Discovery Validation: discovery_validation.md
    - JupyterLab/Notebooks: google_colab_pages.md
  - Project Artifacts: artifacts.md
  - Workflow: git_workflow.md
  - Glossary of Terms: glossary.md
  - Standards: standards.md
  - License: _license.md
